// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Estate_Listing.Models;

namespace Real_Estate_Listing.Migrations
{
    [DbContext(typeof(Real_Estate_ListingContext))]
    [Migration("20191108050005_SeedBooks")]
    partial class SeedBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Real_Estate_Listing.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("SoldDate");

                    b.Property<string>("SoldTo");

                    b.HasKey("Id");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "222 senator",
                            Name = "Greenfield apartments"
                        },
                        new
                        {
                            Id = 2,
                            Address = "222 senator",
                            Name = "Senator apartments"
                        },
                        new
                        {
                            Id = 3,
                            Address = "222 senator",
                            Name = "Jefferson apartments"
                        },
                        new
                        {
                            Id = 4,
                            Address = "222 senator",
                            Name = "lowell apartments"
                        },
                        new
                        {
                            Id = 5,
                            Address = "222 senator",
                            Name = "Forum apartments"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
